### ISSUE TITLE
Implement search functionality

### ISSUE THREAD

**Issue by devesh-verma** [codeuino/social-platform-donut-backend#4]
#### Description
- In this issues, we want to provide basic search functionality in Donut platform. 
- Using this user will be able to search different projects listed under Donut platform

#### Resources

**Comment by Rupeshiya** [comment]
@devesh-verma Can you please give me some hint, how to proceed or how can I implement?
I was trying elasticsearch, it seems to be complex. Any other options?

**Comment by tanujvyas10** [comment]
@devesh-verma sir,I want to work on this issue.
@rupeshiy sir, if you feel right ,can i work on this?

**Comment by Rupeshiya** [comment]
@devesh-verma Please let me know your view on this issue, I would love to implement this.

**Comment by aashaypalliwar** [comment]
Hi, is this issue still open? I see a functionality implemented in the "organization.js" controller that utilizes regex. Here is a suggestion - we may use out of the box functionality provided by mongoDB for text search as mentioned [here](https://docs.mongodb.com/manual/text-search/). All we have to do is create relevant indexes. Thanks!

**Comment by jaskiratsingh2000** [comment]
@devesh-verma @Rupeshiya @vaibhavdaren Any thoughts? If this is still open please comment it here.

**Comment by Rupeshiya** [comment]
Yeah, I have already implemented this using regex.
But @aashaypalliwar Can you please mention some pros or cons for that. If we do by indexing, then I think it would not affect search functionality much, but yes we can gain some speed.
Are you talking about indexing for name or something else as mongo by default do indexing on _id?

**Comment by aashaypalliwar** [comment]
You are right, @Rupeshiya  , the main argument for using mongoDB text indexes is the efficiency. Besides that, mongoDB will do a lot of heavy lifting. In the link in previous comment, it is mentioned about creating a new index named "text" and using it for searching.

Some pros of mongoDB text-search:
1. Sorting as per the relevance to the query string. (Uses internal "textScore")
2. MongoDB utilizes its own tokenizer to tokenize search query with delimiting at not only spaces but other punctuations as well, thus freeing us from dealing with any corner cases.

This was just a suggestion as I know some professionals who decided to explore MongoDB's own functionality when using ElasticSearch was not an option. Please correct me if this is not relevant to the use-case of this project or if regex serves the purpose better.  Thanks!

**Comment by jaskiratsingh2000** [comment]
Thanks this is implemented.
