### ISSUE TITLE
Write testcase for user login route

### ISSUE THREAD

**Issue by capedcrusader23** [codeuino/social-platform-donut-backend#6]
### **What you will need to know?**
Javascript, Node.js, RESTful APIs, Async Programming, Jest.

### **Write test case to ensure that login route is functioning right**
In this task, you are supposed to write a test case for checking the functionality of the login route. To start with this you need to make use of jest which is a testing framework for javascript. 
You can pass dummy data to the function which are required for a user to log in that is `email`, `password`. This test calls the login API with the dummy data and if the login is successful the test passes.

### **Expected Outcome**
The test case should only pass for registered users.
The test case should only pass if correct email and password are provided, which was used by the user while signing up.

### **Resources & References (Where to Start)** 
 - This is most important : [Learn to write test case using async await](https://jestjs.io/docs/en/asynchronous#async-await).
 - Basic of Jest: [Getting started with jest](https://jestjs.io/docs/en/using-matchers)
 - If want to see an implementation of a test case in the project - [Link](https://github.com/devesh-verma/social-platform-donut-backend/blob/abdcc7b270f04d36b318de7f6685414b157f6bcb/test/user.test.js#L38)

### **Extras**
In case you feel confused or need help you can join our channel -  [Codeuino's Website](https://codeuino.slack.com/).

**Comment by devesh-verma** [comment]
Fixed with #37
