### ISSUE TITLE
Signup feature is not available as a user and organization

### ISSUE THREAD

**Issue by tanujvyas10** [codeuino/social-platform-donut-backend#62]
**Describe the enhancement you'd like**
Signup feature should be available both as a user and organization.

**Additional context**
If the issue is valid , I would to work on this

**Comment by devesh-verma** [comment]
@tanujvyas10 signup as user is implemented, signing up as an org need to be implemented.
Signing up as org will not be as straight forward as user signup. We need to have the following for org signup.
1. Required for signing up:
- Org should have a website, which will be reviewed.
- Org should have a medium where they community interacts.

2. After an org has submitted the form the following needs to be done:
- org will receive an email saying there form is under progress.
- codeuino admins will receive an email that xyz org wants to signup.
- we check that its actually an org and not someone pretending to be an org. [We need to think more about this process].
- once we approve org should receive an email saying they can use the platform now.

NOTE: THIS IS ONLY REQUIRED TILL THE TIME CODEUINO IS HOSTING DONUT ON THEIR SERVER's

**Comment by devesh-verma** [comment]
@tanujvyas10 open up a new issue with proper steps that you will be following.
Also, when you are opening an issue please try to give proper name, which is short and consise.

**Comment by tanujvyas10** [comment]
Yes sir thank you,I will keep that in mind
