### ISSUE TITLE
Implement the fix so that when user is created then the eductaion array only have educations info 

### ISSUE THREAD

**Issue by Rupeshiya** [codeuino/social-platform-donut-backend#71]
**Describe the enhancement you'd like**
Implement the fix so that when the user is created then the education array only has educations info and doesn't have any mongoose object id.

**Describe approaches if you have thought of any**
Check the user's schema as well as user controllers to create the new user.

**Additional context**
Should be fixed.

**Comment by tanujvyas10** [comment]
@Rupeshiya I would like to work on this

**Comment by Rupeshiya** [comment]
Great!, Go ahead @tanujvyas10 .
