### ISSUE TITLE
Implement API for projects functionality

### ISSUE THREAD

**Issue by Rupeshiya** [codeuino/social-platform-donut-backend#98]
**Is your feature request related to a problem? Please describe.**
Implement API for projects functionality

**Describe the solution you'd like**
Add REST API for making the functionality of the project functional

**Additional context**
Working on it.

**Comment by JanviMahajan14** [comment]
@Rupeshiya There is already PR for this API #85

**Comment by Rupeshiya** [comment]
Oh, thanks @JanviMahajan14!
I am closing this issue!
